version: "3.3"

services:

    ### Nginx ############################################
    nginx:
        build:
            context: ./nginx
        volumes:
            - ${APPLICATION_BACK}:/var/www
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php
        networks:
            - frontend
            - backend

    ### PHP ############################################
    php:
        build:
            context: ./php
        volumes:
            - ${APPLICATION_BACK}:/var/www
        depends_on:
            - mysql
        networks:
            - backend

    ### MYSQL ############################################
    mysql:
        build:
            context: ./mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${WORKSPACE_TIMEZONE}
        volumes:
            - ${DATA_SAVE_PATH}/mysql:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - backend

    ### NODE ############################################
    node:
        build:
            context: ./node
        volumes:
            - ${APPLICATION_FRONT}:/var/node
        ports:
            - "${FRONT_HTTP_PORT}:3000"
        depends_on:
            - nginx
        networks:
            - frontend

### Networks Setup ############################################
networks:
    frontend:
        driver: "bridge"
    backend:
        driver: "bridge"
